//x = -9999;
//y = -9999;
x2 = x+1 tiles;
y2 = y+1 tiles;
enter = c_null;
stay = c_null;
leave = c_null;
active = false;
step = c_null;
log("help????");
target = "asteroid";
targetx = 10 tiles;
targety = 10 tiles;